### ISSUE TITLE
Training sections

### ISSUE THREAD

**Issue by treiher** [treiher/valens#17]
### Feature Specification

- A training routine will consist of one or multiple sections.
- A section will consist of a sorted list of parts.
- A section part can be either an activity (action/exercise/exertion/work) or rest.
- An activity must be linked to an exercise and may have a duration or a tempo.
- Rest may have a duration. In a workout, the next step will follow after the given time or by button press.
- A section will offer the definition of a number of sets (rounds).
- In a workout, the activities and rest will be repeated according to the specified number of sets of the section.

### Tasks

- [x] Change database model for routines (see also https://docs.sqlalchemy.org/en/14/orm/inheritance.html)
- [x] Change API endpoints in backend
- [x] Change data model in frontend (see also https://serde.rs/enum-representations.html)
- [x] Change frontend for adding routines
- [x] Change creation of workouts
