### ISSUE TITLE
Client-Side Rendering

### ISSUE THREAD

**Issue by treiher** [treiher/valens#20]
Use CSR instead of SSR to improve interactivity.

### Considered Options

- [Flutter](https://flutter.dev/)
    - Pro: Active development of language (Dart) and framework by Google
    - Pro: Popular
- [Seed](https://seed-rs.org/)
    - Pro: Language (Rust) actively developed
    - Pro: Interesting language
    - Con: Framework mainly developed by single person
    - Con: Experimental
- [Elm](https://elm-lang.org/)
    - Pro: Interesting language and concepts
    - Con: Mainly developed by single person

### Decision Outcome

Seed

### Tasks

- [x] Add REST-like API
- [x] Reimplement existing functionality on client side
- [x] Add detection of version mismatch between frontend and backend
- [x] Move plotting into frontend
- [x] Remove SSR
